import { VillageNode, TelemetryHistoryPoint, AlertRecord, SmsRecipient } from '../types';

export const INITIAL_NODES: VillageNode[] = [
  {
    id: 'NODE-01',
    name: 'Panchayat Bhavan / Central Hub',
    marathiName: 'ग्रामपंचायत भवन - मुख्य केंद्र',
    zone: 'Zone-A (Administrative Core)',
    isPrototype: true, // Physical hardware prototype
    mapCoords: { x: 48, y: 52 },
    status: 'SAFE',
    telemetry: {
      temperature: 29.8,
      pressure: 1012.4,
      waterLevel: 28.5,
      soilMoisture: 45.2,
      vibration: 0.35,
    },
    health: {
      isOnline: true,
      batteryPercent: 96,
      batteryVoltage: 4.12,
      signalRssi: -58,
      signalQuality: 'EXCELLENT',
      commProtocol: 'Direct USB-Serial / LoRaWAN Gateway',
      lastUpdated: 'Just now (Real-time Live)',
      uptimeDays: 14,
      packetsReceived: 18450,
      packetLossPercent: 0.02,
    },
  },
  {
    id: 'NODE-02',
    name: 'North Bund / Nallah Inflow',
    marathiName: 'उत्तर बंधारा / नाला ओढा',
    zone: 'Zone-B (River Inundation Risk)',
    isPrototype: false,
    mapCoords: { x: 26, y: 22 },
    status: 'SAFE',
    telemetry: {
      temperature: 28.4,
      pressure: 1011.8,
      waterLevel: 42.0,
      soilMoisture: 58.4,
      vibration: 0.42,
    },
    health: {
      isOnline: true,
      batteryPercent: 88,
      batteryVoltage: 3.98,
      signalRssi: -72,
      signalQuality: 'GOOD',
      commProtocol: 'LoRaWAN 868 MHz (Sub-GHz)',
      lastUpdated: '45s ago (Pre-fed Grid)',
      uptimeDays: 28,
      packetsReceived: 34210,
      packetLossPercent: 0.45,
    },
  },
  {
    id: 'NODE-03',
    name: 'Zilla Parishad Primary School',
    marathiName: 'जि. प. प्राथमिक शाळा केंद्र',
    zone: 'Zone-C (Community Shelter)',
    isPrototype: false,
    mapCoords: { x: 74, y: 38 },
    status: 'SAFE',
    telemetry: {
      temperature: 30.5,
      pressure: 1012.8,
      waterLevel: 8.0,
      soilMoisture: 38.0,
      vibration: 0.28,
    },
    health: {
      isOnline: true,
      batteryPercent: 92,
      batteryVoltage: 4.05,
      signalRssi: -64,
      signalQuality: 'GOOD',
      commProtocol: 'LoRaWAN 868 MHz (Sub-GHz)',
      lastUpdated: '1m ago (Pre-fed Grid)',
      uptimeDays: 45,
      packetsReceived: 56100,
      packetLossPercent: 0.12,
    },
  },
  {
    id: 'NODE-04',
    name: 'Gauthan High Ground / Water Tank',
    marathiName: 'गावठाण टेकडी / जलकुंभ',
    zone: 'Zone-D (Elevated Safe Datum)',
    isPrototype: false,
    mapCoords: { x: 58, y: 20 },
    status: 'SAFE',
    telemetry: {
      temperature: 29.1,
      pressure: 1010.5,
      waterLevel: 2.0,
      soilMoisture: 32.5,
      vibration: 0.18,
    },
    health: {
      isOnline: true,
      batteryPercent: 95,
      batteryVoltage: 4.10,
      signalRssi: -52,
      signalQuality: 'EXCELLENT',
      commProtocol: 'LoRaWAN 868 MHz (Sub-GHz)',
      lastUpdated: '1m 20s ago (Pre-fed Grid)',
      uptimeDays: 60,
      packetsReceived: 78900,
      packetLossPercent: 0.08,
    },
  },
  {
    id: 'NODE-05',
    name: 'Agricultural Sector / Canal Sluice',
    marathiName: 'कृषी शिवार / कालवा विसर्ग',
    zone: 'Zone-E (Agrarian Drainage)',
    isPrototype: false,
    mapCoords: { x: 22, y: 76 },
    status: 'SAFE',
    telemetry: {
      temperature: 31.2,
      pressure: 1012.1,
      waterLevel: 34.0,
      soilMoisture: 64.0,
      vibration: 0.38,
    },
    health: {
      isOnline: true,
      batteryPercent: 84,
      batteryVoltage: 3.92,
      signalRssi: -78,
      signalQuality: 'FAIR',
      commProtocol: 'LoRaWAN 868 MHz (Sub-GHz)',
      lastUpdated: '2m ago (Pre-fed Grid)',
      uptimeDays: 31,
      packetsReceived: 38400,
      packetLossPercent: 0.62,
    },
  },
  {
    id: 'NODE-06',
    name: 'Forest Fringe / Biomass Zone',
    marathiName: 'वन सीमा / जैवभार क्षेत्र',
    zone: 'Zone-F (Slope & Vibration Watch)',
    isPrototype: false,
    mapCoords: { x: 80, y: 78 },
    status: 'SAFE',
    telemetry: {
      temperature: 32.8,
      pressure: 1011.6,
      waterLevel: 5.0,
      soilMoisture: 42.1,
      vibration: 0.65,
    },
    health: {
      isOnline: true,
      batteryPercent: 79,
      batteryVoltage: 3.86,
      signalRssi: -84,
      signalQuality: 'FAIR',
      commProtocol: 'LoRaWAN 868 MHz (Sub-GHz)',
      lastUpdated: '2m 15s ago (Pre-fed Grid)',
      uptimeDays: 22,
      packetsReceived: 27100,
      packetLossPercent: 0.88,
    },
  },
];

// Short, concise list of historical hazard alerts (Safe, Watch, Risk stages only)
export const INITIAL_HISTORICAL_ALERTS: AlertRecord[] = [
  {
    id: 'ALT-1092',
    timestamp: '2026-09-20 18:42:10 IST',
    nodeId: 'NODE-02',
    nodeName: 'North Bund / Nallah Inflow',
    severity: 'WATCH',
    hazardType: 'FLOOD',
    title: 'Water Level Exceeded 55cm Advisory Mark',
    description: 'Upstream barrage discharge triggered seasonal watch threshold. Flow returned to baseline within 40 minutes.',
    acknowledged: true,
  },
  {
    id: 'ALT-1088',
    timestamp: '2026-09-18 14:15:02 IST',
    nodeId: 'NODE-05',
    nodeName: 'Agricultural Sector / Canal Sluice',
    severity: 'WATCH',
    hazardType: 'SOIL_MOISTURE',
    title: 'Soil Moisture Reached 76% Runoff Level',
    description: 'Canal sluice irrigation raised local ground saturation into advisory stage. Normalized overnight.',
    acknowledged: true,
  },
  {
    id: 'ALT-1081',
    timestamp: '2026-09-14 06:30:19 IST',
    nodeId: 'NODE-01',
    nodeName: 'Panchayat Bhavan / Central Hub',
    severity: 'SAFE',
    hazardType: 'SYSTEM',
    title: 'Physical Trigger Calibrator Routine Check',
    description: 'Physical sensor calibrator diagnostics verified across temperature, pressure, water level, soil moisture, and vibration.',
    acknowledged: true,
  },
];

export const DEFAULT_SMS_RECIPIENTS: SmsRecipient[] = [
  {
    role: 'Sarpanch (Village Head)',
    name: 'Shri Anand R. Patil',
    mobile: '+91 98220 XXXXX',
    status: 'SENT',
    deliveryTime: 'Idle / Standby',
  },
  {
    role: 'Panchayat Secretary (Gram Sevak)',
    name: 'Smt. Sunita M. Gaikwad',
    mobile: '+91 94231 XXXXX',
    status: 'SENT',
    deliveryTime: 'Idle / Standby',
  },
  {
    role: 'Talathi (Revenue Inspector)',
    name: 'Shri Vilas S. Deshmukh',
    mobile: '+91 98904 XXXXX',
    status: 'SENT',
    deliveryTime: 'Idle / Standby',
  },
  {
    role: 'Medical Officer (Primary Health Centre)',
    name: 'Dr. Priya K. Joshi',
    mobile: '+91 97632 XXXXX',
    status: 'SENT',
    deliveryTime: 'Idle / Standby',
  },
  {
    role: 'Village Kotwal / Disaster Volunteer Team',
    name: 'Shri Ganesh T. Jadhav',
    mobile: '+91 91588 XXXXX',
    status: 'SENT',
    deliveryTime: 'Idle / Standby',
  },
];

export function generateInitialTrendData(): TelemetryHistoryPoint[] {
  const points: TelemetryHistoryPoint[] = [];
  const now = Date.now();
  for (let i = 24; i >= 0; i--) {
    const time = new Date(now - i * 5 * 60 * 1000); // 5 min increments
    const hour = time.getHours().toString().padStart(2, '0');
    const min = time.getMinutes().toString().padStart(2, '0');
    points.push({
      timestamp: time.toISOString(),
      timeLabel: `${hour}:${min}`,
      temperature: Math.round((29 + Math.sin(i * 0.15) * 2 + Math.random() * 0.5) * 10) / 10,
      pressure: Math.round((1012 + Math.cos(i * 0.1) * 1.5 + Math.random() * 0.4) * 10) / 10,
      waterLevel: Math.round((26 + Math.sin(i * 0.3) * 3 + Math.random() * 2) * 10) / 10,
      soilMoisture: Math.round((45 + Math.sin(i * 0.2) * 4 + Math.random() * 2) * 10) / 10,
      vibration: Math.round((0.3 + Math.random() * 0.15) * 100) / 100,
    });
  }
  return points;
}
